### ISSUE TITLE
建议升级okhttp 3.0版本

### ISSUE THREAD

**Issue by axeon** [qiniu/java-sdk#196]
其他的库都升级到okhttpd 3.0了，为了qiniu还保留了okhttp 2.7.2

**Comment by longbai** [comment]
我们会考虑做一次升级

**Comment by DolphinBoy** [comment]
`Exception in thread "main" java.lang.IncompatibleClassChangeError: Found class com.squareup.okhttp.Connection, but interface was expected
	at com.qiniu.http.Client$1.intercept(Client.java:39)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:802)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:683)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at com.qiniu.http.Client.send(Client.java:195)
	at com.qiniu.http.Client.get(Client.java:85)
	at com.qiniu.storage.BucketManager.get(BucketManager.java:314)
	at com.qiniu.storage.BucketManager.listFiles(BucketManager.java:113)
	at com.test.QiniuDown.main(QiniuDown.java:22)
`

**Comment by longbai** [comment]
主版本 会升级到3 #200

**Comment by longbai** [comment]
已经升级发布 @axeon @DolphinBoy
