### ISSUE TITLE
到底用的是哪个版本？

### ISSUE THREAD

**Issue by DolphinBoy** [qiniu/java-sdk#199]
最新版报错
`
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/RequestBody
	at com.qiniu.storage.BucketManager.<init>(BucketManager.java:29)
	at com.test.QiniuDown.main(QiniuDown.java:19)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.RequestBody
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 2 more

`

**Comment by DolphinBoy** [comment]
`
![image](https://cloud.githubusercontent.com/assets/1713001/14808742/6aee5d32-0bba-11e6-8b30-ded5e0e01713.png)

`

**Comment by DolphinBoy** [comment]
不是最新版也报错
![image](https://cloud.githubusercontent.com/assets/1713001/14808750/7ecfff2c-0bba-11e6-8f23-a794ff510002.png)

`
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found class com.squareup.okhttp.Connection, but interface was expected
	at com.qiniu.http.Client$1.intercept(Client.java:39)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:802)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:683)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at com.qiniu.http.Client.send(Client.java:195)
	at com.qiniu.http.Client.get(Client.java:85)
	at com.qiniu.storage.BucketManager.get(BucketManager.java:314)
	at com.qiniu.storage.BucketManager.listFiles(BucketManager.java:113)
	at com.test.QiniuDown.main(QiniuDown.java:22)

`

**Comment by longbai** [comment]
建议2.7 及以上，我们会尽快升级到okhttp3

**Comment by longbai** [comment]
主版本 会升级到3 #200
