### ISSUE TITLE
抓取网络资源到空间示例报错

### ISSUE THREAD

**Issue by fishinhouse** [qiniu/java-sdk#310]
pom.xml
```

               <dependency>
		    <groupId>com.qiniu</groupId>
		    <artifactId>qiniu-java-sdk</artifactId>
		    <version>7.2.7</version>
		</dependency>
```
JAVA Code:

```
//构造一个带指定Zone对象的配置类
Configuration cfg = new Configuration(Zone.zone0());
//...其他参数参考类注释
String accessKey = "your access key";
String secretKey = "your secret key";
String bucket = "your bucket name";
String key = "your file key";
String remoteSrcUrl = "http://devtools.qiniu.com/qiniu.png";
Auth auth = Auth.create(accessKey, secretKey);
BucketManager bucketManager = new BucketManager(auth, cfg);
//抓取网络资源到空间
try {
    FetchRet fetchRet = bucketManager.fetch(remoteSrcUrl, bucket, key);
    System.out.println(fetchRet.hash);
    System.out.println(fetchRet.key);
    System.out.println(fetchRet.mimeType);
    System.out.println(fetchRet.fsize);
} catch (QiniuException ex) {
    System.err.println(ex.response.toString());
}
```

Junit结果：
{ResponseInfo:com.qiniu.http.Response@42a05533,status:404, reqId:yw8AANnVmpiC19wU, xlog:IO/404, xvia:, adress:iovip-z1.qbox.me/106.38.227.14:80, duration:0.000000 s, error:incorrect region}

**Comment by fishinhouse** [comment]
//捕获异常信息
 e.printStackTrace();
···
com.qiniu.common.QiniuException: http://iovip-z1.qbox.me/fetch/aHR0cDovL2RldnRvb2xzLnFpbml1LmNvbS9xaW5pdS5wbmc=/to/YmJzLWltYWdlOnFpbml1LnBuZw==  
{ResponseInfo:com.qiniu.http.Response@c0013b8,status:404, reqId:KDkAANPkW7EQ2NwU, xlog:IO/404, xvia:, adress:iovip-z1.qbox.me/106.38.227.28:80, duration:0.000000 s, error:incorrect region}  
{"error":"incorrect region"}
	at com.qiniu.http.Client.send(Client.java:270)
	at com.qiniu.http.Client.post(Client.java:200)
	at com.qiniu.http.Client.post(Client.java:183)
	at com.qiniu.storage.BucketManager.post(BucketManager.java:444)
	at com.qiniu.storage.BucketManager.ioPost(BucketManager.java:429)
	at com.qiniu.storage.BucketManager.fetch(BucketManager.java:341)
	at com.wx.wxwebmagic.web.topic.QiNiuTools.fetchImage(QiNiuTools.java:43)
	at com.wx.wxwebmagic.WxwebmagicApplicationTests.qiNiuToolsTest(WxwebmagicApplicationTests.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
···

**Comment by jemygraw** [comment]
构建Configuration对象的时候，请使用
```
//构造一个带指定Zone对象的配置类
Configuration cfg = new Configuration(Zone.zone1());
```
因为，你的空间是华北空间

**Comment by fishinhouse** [comment]
@jemygraw 你好，谢谢你的回复。
我试过两种Zone都会抛异常。
第一种：Zone.zone1()
---
```
Configuration c = new Configuration(Zone.zone1());
```
异常如下：
```
com.qiniu.common.QiniuException: http://iovip-z1.qbox.me/fetch/aHR0cDovL2RldnRvb2xzLnFpbml1LmNvbS9xaW5pdS5wbmc=/to/YmJzLWltYWdlOnFpbml1LnBuZw==  
{ResponseInfo:com.qiniu.http.Response@7742a276,status:404, reqId:AEUAAEHOD2SSDd0U, xlog:IO/404, xvia:, adress:iovip-z1.qbox.me/106.38.227.25:80, duration:0.000000 s, error:incorrect region}  
{"error":"incorrect region"}
	at com.qiniu.http.Client.send(Client.java:270)
	at com.qiniu.http.Client.post(Client.java:200)
	at com.qiniu.http.Client.post(Client.java:183)
	at com.qiniu.storage.BucketManager.post(BucketManager.java:444)
	at com.qiniu.storage.BucketManager.ioPost(BucketManager.java:429)
	at com.qiniu.storage.BucketManager.fetch(BucketManager.java:341)
	at com.wx.wxwebmagic.web.topic.QiNiuTools.fetchImage(QiNiuTools.java:42)
	at com.wx.wxwebmagic.WxwebmagicApplicationTests.qiNiuToolsTest(WxwebmagicApplicationTests.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
第二种：Zone.zone0()
---
```
Configuration c = new Configuration(Zone.zone0());
```
异常如下：
```
com.qiniu.common.QiniuException: http://iovip.qbox.me/fetch/aHR0cDovL2RldnRvb2xzLnFpbml1LmNvbS9xaW5pdS5wbmc=/to/YmJzLWltYWdlOnFpbml1LnBuZw==  
{ResponseInfo:com.qiniu.http.Response@2ce47652,status:404, reqId:4UIAAAtsEErGDd0U, xlog:IO/404, xvia:, adress:iovip.qbox.me/115.231.183.178:80, duration:0.000000 s, error:incorrect region}  
{"error":"incorrect region"}
	at com.qiniu.http.Client.send(Client.java:270)
	at com.qiniu.http.Client.post(Client.java:200)
	at com.qiniu.http.Client.post(Client.java:183)
	at com.qiniu.storage.BucketManager.post(BucketManager.java:444)
	at com.qiniu.storage.BucketManager.ioPost(BucketManager.java:429)
	at com.qiniu.storage.BucketManager.fetch(BucketManager.java:341)
	at com.wx.wxwebmagic.web.topic.QiNiuTools.fetchImage(QiNiuTools.java:42)
	at com.wx.wxwebmagic.WxwebmagicApplicationTests.qiNiuToolsTest(WxwebmagicApplicationTests.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
### 成功做法:
```
Configuration c = new Configuration(Zone.autoZone());
```
自动选择存储区域。

**Comment by jemygraw** [comment]
你根据你的空间机房使用不同的zone测试看看，我这里测试没问题。
华东 Zone0
华北 Zone1
华南 Zone2
北美 ZoneNa0
