### ISSUE TITLE
新编译的api上传不了文件，报错了

### ISSUE THREAD

**Issue by xinqiyang** [qiniu/java-sdk#321]
新编译的api上传不了文件了。 

出错信息如下，为撒，之前都是好好的，结果今天就上传不上去了。 

环境spring boot 1.5.2
系统 centos 7 
jdk:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode) 

ls ~/.m2/repository/com/qiniu/qiniu-java-sdk/
7.0.0   7.0.2    7.0.4.2  7.0.8  7.1.2  7.2.10  7.2.5  7.2.9                               maven-metadata-spring-releases.xml.sha1
7.0.1   7.0.3    7.0.5    7.0.9  7.1.3  7.2.2   7.2.6  maven-metadata-central.xml          resolver-status.properties
7.0.10  7.0.4    7.0.6    7.1.0  7.2.0  7.2.3   7.2.7  maven-metadata-central.xml.sha1
7.0.11  7.0.4.1  7.0.7    7.1.1  7.2.1  7.2.4   7.2.8  maven-metadata-spring-releases.xml

加载7.2.10 后报错了直接无法上传了，这块发布新版本之前没有测试过么？

java.lang.NoSuchMethodError: okio.BufferedSource.readUtf8LineStrict(J)Ljava/lang/String;
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.qiniu.http.Client$1.intercept(Client.java:73)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.qiniu.http.Client.send(Client.java:263)
	at com.qiniu.http.Client.get(Client.java:153)
	at com.qiniu.http.Client.get(Client.java:148)
	at com.qiniu.common.AutoZone.getZoneJson(AutoZone.java:52)
	at com.qiniu.common.AutoZone.queryZoneInfo(AutoZone.java:67)
	at com.qiniu.common.AutoZone.queryZoneInfo(AutoZone.java:89)
	at com.qiniu.common.AutoZone.getUpHttp(AutoZone.java:101)
	at com.qiniu.storage.Configuration.upHost(Configuration.java:103)
	at com.qiniu.storage.FormUploader.upload(FormUploader.java:68)
	at com.qiniu.storage.UploadManager.put(UploadManager.java:175)
	at com.qiniu.storage.UploadManager.put(UploadManager.java:154)
	at com.coinphd.client.QiniuClient.putObject(QiniuClient.java:64)
	at com.coinphd.client.QiniuClient$$FastClassBySpringCGLIB$$7c6699ca.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jemygraw** [comment]
你看看spring boot依赖的okhttp是不是和java sdk的okhttp有版本冲突。

**Comment by hktry** [comment]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath /> 
	</parent>

		<dependency>
			<groupId>com.qiniu</groupId>
			<artifactId>qiniu-java-sdk</artifactId>
			<version>7.2.10</version>
		</dependency>

这边测试了一波是没问题的，你检查下其他的依赖看下是否有冲突
