### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException异常问题

### ISSUE THREAD

**Issue by daxiong294** [qiniu/java-sdk#361]
使用java-sdk时出现这个错误：javax.net.ssl.SSLPeerUnverifiedException: Hostname uc.qbox.me not verified:
可有遇到过这种情况？（没有引用happy-dns-java包）

**Comment by forrest-mao** [comment]
目前使用最新版本的 java sdk 是否还会遇到类似问题。

**Comment by wangaowell** [comment]
我使用 JDK 8 ，在 spring cloud 项目中使用上传，报
`Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)

	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

	at sun.security.validator.Validator.validate(Validator.java:260)

	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)

	... 142 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)

	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)

	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)`
