### ISSUE TITLE
SDK访问服务端接口存在SSL相关错误

### ISSUE THREAD

**Issue by Mystery00** [qiniu/java-sdk#607]
```
Caused by: com.qiniu.common.QiniuException: java.net.ConnectException: Failed to connect to uc.qbox.me/240e:97c:38:500:3:0:0:3f4:443 on uc.qbox.me/240e:97c:38:500:3:0:0:3f4:443
	at com.qiniu.http.Client.send(Client.java:416)
	at com.qiniu.http.Client.get(Client.java:195)
	at com.qiniu.http.Client.get(Client.java:190)
	at com.qiniu.storage.AutoRegion.queryRegionInfoFromServerIfNeeded(AutoRegion.java:54)
	at com.qiniu.storage.AutoRegion.queryRegionInfo(AutoRegion.java:93)
	at com.qiniu.storage.AutoRegion.queryRegionInfo(AutoRegion.java:122)
	at com.qiniu.storage.AutoRegion.getRsHost(AutoRegion.java:204)
	at com.qiniu.storage.ConfigHelper.rsHost(ConfigHelper.java:55)
	at com.qiniu.storage.BucketManager.rsPost(BucketManager.java:1087)
	at com.qiniu.storage.BucketManager.statResponse(BucketManager.java:279)
	at com.qiniu.storage.BucketManager.stat(BucketManager.java:272)
	at com.xxx.yyy(XXX.java:110)
	... 98 common frames omitted
Caused by: java.io.IOException: java.net.ConnectException: Failed to connect to uc.qbox.me/240e:97c:38:500:3:0:0:3f4:443 on uc.qbox.me/240e:97c:38:500:3:0:0:3f4:443
	at com.qiniu.http.Client$3.intercept(Client.java:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.qiniu.http.Client.send(Client.java:414)
	... 109 common frames omitted
Caused by: java.net.ConnectException: Failed to connect to uc.qbox.me/240e:97c:38:500:3:0:0:3f4:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.qiniu.http.Client$3.intercept(Client.java:116)
	... 113 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
		at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
		at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
		at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
		at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
		at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
		... 126 common frames omitted
	Suppressed: java.net.ConnectException: Failed to connect to uc.qbox.me/240e:97c:38:500:3:0:0:3f3:443
		... 128 common frames omitted
	Caused by: java.net.ConnectException: Network unreachable (connect failed)
		at java.net.PlainSocketImpl.socketConnect(Native Method)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		at java.net.Socket.connect(Socket.java:607)
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
		... 127 common frames omitted
Caused by: java.net.ConnectException: Network unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 127 common frames omitted
```

使用的SDK版本 com.qiniu:qiniu-java-sdk:7.15.1

**Comment by bachue** [comment]
@Mystery00  这只是普通的网络原因导致的 SSL 握手错误吧，重试即可？

**Comment by Mystery00** [comment]
应该是跟我的运行环境有点关系，在容器里面不行，在开发电脑上可以

Bachue Zhou ***@***.***> 于2024年9月5日周四 17:18写道：

**Comment by bachue** [comment]
@Mystery00 是不是容器里的 JRE 没有正确配置证书？
